### ISSUE TITLE
parsing time "Invalid date" as "2006-01-02"

### ISSUE THREAD

**Issue by mredigonda** [gammons/todolist#90] opened 2017-08-15 02:47 UTC
parsing time "Invalid date" as "2006-01-02": cannot parse "Invalid date" as "2006"
This may due to the corruption of .todos.json file.

This error pops up when I try to list my tasks (`todolist list`, `todolist list by project`, `todolist list by context`). 

It started to happen after using the web version (opened with `todolist web`), maybe it could be cause by manipulating both the web version and the CLI at the same time, it seems that some action in the web version corrupted the .todos.json files. 

Web version is also **not working** (it doesn't let you add tasks nor check them as completed), but at least it is displaying (I think) all of the tasks. 

Great software, by the way :+1: 

**EDIT**: I revised the problem and updated the issue.
**EDIT**: Examining the .todos.json file, it seems that one of the events has an "Invalid date" in the "due" property, that was expected, but also, the task that has this value also has a period: "." in it, could this has something to do with the error? I think I have added the task, and after manipulating it (by changing date from web interface) it crashed. After manually repairing the .todos.json file, now everything is working fine.

**Comment by NonerKao** [comment] 2017-08-28 03:05
Could you please recall the steps you might have taken that triggered the problem or the file corruption?   We don't know how to reproduce this bug from your description.

**Comment by mredigonda** [comment] 2017-08-28 22:59
I'm able to reproduce the bug, but that may be because of the fact that I'm using and older version (though I'm not able to update it via apt-get). I just create an event from "00:00" to "00:00" with a description equal to "00:10". This highlights the day in which I made the event, but no description of the event is showed anywhere except in the file I get when I run the export command.

**Comment by gammons** [comment] 2017-08-29 00:21
ah, darn.  The "invalid date" thing with `todolist web` was a problem in previous versions of todolist.  I am sad to hear it has come back.

**Comment by gammons** [comment] 2017-08-29 00:22
@mredigonda what version of todolist are you using?  I know this was fixed in a recent version.

**Comment by mredigonda** [comment] 2017-08-29 22:04
Oh wait, I'm afraid I'm confused. Please ignore my previous message, it says things that makes no sense like 'from "00:00" to "00:00"', I confused repos with calcurse, which had another problem about dates. I'm really sorry about that.

I couldn't reproduce this bug. I thought it could have to do with multiple instances of "todolist web" running on different tabs, or interacting from the command line and the web version at the same time.

**Comment by dnel** [comment] 2017-10-31 16:38
I've had this problem today on 0.8 from Brew. I don't know at what point it broke but I have had the web view open today so it may be that, I needed to remove "Invalid date" from two tasks in the json file manually to get it working again.

**Comment by NonerKao** [comment] 2018-01-10 14:01
@dnel Is this still an issue? Or is any other Mac user suffering from this?

**Comment by dnel** [comment] 2018-01-10 16:11
I've not seen it since, but I haven't been using web view for a while due to it being broken.

**Comment by gammons** [comment] 2018-08-04 12:45
web view is fixed!  Please re-open this issue if you see the same problem with the web view.

**Closed by gammons** 2018-08-04 12:45 UTC
