### ISSUE TITLE
new "ln" option weird spacing

### ISSUE THREAD

**Issue by UnixMonky** [gammons/todolist#98] opened 2017-09-27 15:14 UTC
![screenshot from 2017-09-27 11-10-15](https://user-images.githubusercontent.com/6799707/30921426-7bef5c3c-a374-11e7-8583-b8718a5ba722.png)
It looks like when the 'ln' option is used to show all todos and their notes, the date/task field are being pushed to the right to make room for the note fields, even though those are on a separate line.

I would expect the main todo line (with the number, [ ] status and date) to be formatted the same whether I'm viewing the notes of a task or not.

p.s. even with this, I'm loving the notes!

**Comment by NonerKao** [comment] 2017-09-27 15:31
Thanks for the kind words!
I will dig into this next week.  It looks like something to do with the `tabwriter.Writer` ( like #48 again? ), but I am not sure for now...

**Comment by gwelr** [comment] 2017-09-27 15:41
I second @UnixMonky observations: 
![selection_104](https://user-images.githubusercontent.com/384931/30922963-f958ffa8-a3aa-11e7-85ed-9d179a732ba7.jpg)

The todo description is pushed as far as the longest note.

**Comment by NonerKao** [comment] 2017-10-02 15:04
I provide a quick fix in #108 , the effect of which is basically like the follow picture:
![2017-10-02 22-26-59](https://user-images.githubusercontent.com/7981456/31082596-0e4b2424-a755-11e7-8a70-2a324267975f.png)

The root cause is that, the **notes** are aligned to the same column as the **due days**, so a very long note would push the subjects to the right.

The patch #108 tries to place the notes at the same column as the subjects, but due to similar reason to #48 (`tabwriter` takes the length of escape sequence into account), the final output turns out with one indentation shift in the figure, and may differ in other cases.  

We will never have a good looking output if we don't fix this.  This is really bothersome. I will do some survey if there are any "escape-sequence-aware tabwriter", or just do one myself and change the dependency.

Appendix: The basic description of what `tabwriter`does in this project

After we do `new(tabwriter.Writer)` and `Init(...)`,  the writer will then buffer all `fmt.Fprintf`ed strings.  When the program flow hits the `Flush` function, the writer will them decide how to organize the buffer into column-based data and output them to `os.Stdout`.

**Comment by gammons** [comment] 2018-08-04 12:43
I believe this should be fixed now.  Please re-open if not!  Also, I think #133 will help with the other spacing issues outlined in the screenshots.

**Closed by gammons** 2018-08-04 12:43 UTC
